"""wip

Revision ID: 1de37221e069
Revises: da0a77ae0d6c
Create Date: 2025-12-07 01:13:45.120409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de37221e069'
down_revision: Union[str, None] = 'da0a77ae0d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurances', sa.Column('policy_type', sa.String(), nullable=False))
    op.alter_column('insurances', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('insurances', 'end_date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('insurances', 'end_date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('insurances', 'start_date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('insurances', 'policy_type')
    # ### end Alembic commands ###
